apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: {{ .Values.frontend.env.REACT_APP_BACKEND_URL | quote }}
