frontend:
  replicas: 1
  image:
    repository: doominno/mern-frontend
    tag: "1.1.0"
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  containerPort: 80 

backend:
  replicas: 1
  image:
    repository: doominno/mern-backend
    tag: "1.1.0"
  service:
    type: ClusterIP
    port: 5000
  containerPort: 5000 
