# backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
type: Opaque
stringData:
  MONGO_URI: mongodb://usuario:Usuario1.@my-mongo-mongodb.production.svc.cluster.local:27017/miapp

