# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: backend
          image: doominno/mern-backend:1.0.3
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
            - name: PORT
              value: "5000"
