apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
      - name: frontend
        image: doominno/mern-frontend:1.0.4
        ports:
        - containerPort: 80
